---
title: "01-clean-data-synt"
author: "Beatriz Couto Ribeiro"
date: "2024-11-21"
output: html_document
editor_options: 
  chunk_output_type: console
---


# 0. Clean Environment
```{r}

rm(list = ls())

```


## 1.1. Set Folder
```{r}

getwd()

setwd("C:/Users/wb618493/OneDrive - WBG/Documents/ASA - Privitazation of Distribution/Brazil/Data/DATA_ANEEL")

```


## 1.2. Install and load packages
```{r}

if (!require("pacman")) install.packages("pacman") #pacman will not accept a character vector so the same packages are repeated

pacman::p_load(tidyverse, #packages for data science
               plm, #estimation of linear panel models
               ggplot2,  #creating graphics
               lmtest, #testing linear regression Models
               tseries, #Augmented Dickey-Fuller Test
               clubSandwich, #robustness checks
               sandwich, #robustness checks
               stargazer, #formatting tables for publications
               devtools, #web developer tools 
               rmarkdown, #reproducibility
               tidyr,  #changing the shape and hierarchy of a data set
               dplyr, #grammar of data manipulation
               Synth, #importing and exporting
               SCtools, #extensions for Synthetic Controls Analysis
               MSCMT,  #Multivariate Synthetic Control Method
               gsynth, #generalized Synthetic Control Method
               panelView, #visualize data panels
               httr, # call url
               jsonlite, # use API
               DataExplorer, # Automated Exploratory Data Analysis
               kableExtra, #formatting tables
               webshot, #enable table exportation with kableExtra
               ggrepel, #labels with ggplot
               ggthemes, #different graph themes for ggplot
               ggpubr, #put figures together
               car, # check multicollinearity
               lmtest, # robust standard errors
               #scpi, #  SCM with Multiple Treated Units and Staggered Adoption
               synthdid, # Synthetic Difference in Differences Estimation
               plm, # linear models for panel data
               abind, # Combine Multidimensional Arrays
               readxl, #read xls files
               data.table, # Fast aggregation of large data
               basedosdados,
               bigQueryR,
               googleAuthR,
               readxl, # read excel
               openxlsx) # write xlsx file 


```


# 2. Data

## 2.0. General Datasets
```{r}

# 1. Name Harmonization File
df_names <- read.csv("names_before_after_privatization_BR_cnpj_concession_11-19-2024.csv")

# 2. Inflation Data
ipca_monthly_trans <- read.csv("ipca_deflator_monthly.csv")


```

### 4.1.1. SAMP - ANEEL: Retrieve inflation data IPCA from Base dos dados: https://basedosdados.org/dataset/ea4d07ca-e779-4d77-bcfa-b0fd5ebea828?table=f1fd2eb7-467a-403b-8f1c-2de8eff354e6
```{r}
## set the google cloud console ID and project
# basedosdados::set_billing_id("inflation-ipca")

#deflate Tariff with monthly IPCA
#create monthly deflator
# ipca_monthly <- basedosdados::read_sql(query = "SELECT ano, mes, indice, variacao_anual, variacao_doze_meses FROM basedosdados.br_ibge_ipca.mes_brasil")

# ipca_monthly_trans<-ipca_monthly%>%arrange(ano,mes)
# ipca_monthly_trans<-ipca_monthly_trans%>%mutate(deflator93=indice/100)%>%
#   mutate(deflator122023=deflator93[ano==2023 & mes==12]/deflator93)
# ipca_monthly_trans<-ipca_monthly_trans%>%select(ano,mes,deflator122023)
# ipca_monthly_trans <- type.convert(ipca_monthly_trans, as.is = TRUE) 
# 
# colnames(ipca_monthly_trans) <- c("Year", "Month", "deflator122023")
# 
# write.csv(ipca_monthly_trans, "ipca_deflator_monthly.csv", row.names = FALSE)

```



## 2.1.SAMP - ANEEL
```{r}

# 1. File Reading and Combining
file_names <- paste0("samp_aneel_", c("1991-2002", "2003-2007", "2008-2011", "2012-2015", "2016-2020", "2021-2023"), ".xlsx")
samp_data <- lapply(file_names, read_excel)
samp_2003_2023 <- bind_rows(samp_data[2:6])  # Combine 2003–2023 datasets
samp_1991_2002 <- samp_data[[1]]



# 4. Data Preparation for SAMP
## 4.1 Format 1991-2002 Data
samp_1991_2002 <- samp_1991_2002 %>%
  mutate(MêsAno = as.Date(MêsAno),
         Year = year(MêsAno),
         Month = month(MêsAno)) %>%
  select(-MêsAno)

## 4.2 Rename Columns and Calculate Variables
samp_1991_2002 <- samp_1991_2002 %>%
  rename_with(~ c("Tension", "Firm", "Class", "Consumers", "ConsumptionEnergy", "Demand", "Revenue", "Tax", "Year", "Month")) %>%
  mutate(RevenueTax = Revenue + Tax,
         Demand = NULL)  # Remove Demand as it's unclear

samp_2003_2023 <- samp_2003_2023 %>%
  rename_with(~ c("Firm", "Year", "Month", "Tension", "Class", "ConsumptionEnergy", "Revenue", "RevenueTax", "Consumers")) %>%
  mutate(Tax = RevenueTax - Revenue)

## 4.3 Merge Datasets
samp_1991_2023 <- bind_rows(
  samp_2003_2023 %>% mutate(across(c(Year, Month), as.numeric)),
  samp_1991_2002
)

# 5. Harmonize Variables
harmonize_tension <- function(tension) {
  case_when(
    str_detect(tension, "Residencial Baixa Renda") ~ "B1 - Residencial Baixa Renda",
    str_detect(tension, "Iluminação Pública") ~ "B4",
    str_detect(tension, "Rural") ~ "B2",
    str_detect(tension, "A4") ~ "A4 (2,3 a 25 kV)",
    str_detect(tension, "A2") ~ "A2 (88 a 138 kV)",
    str_detect(tension, "A3a") ~ "A3a (30 kV a 44 kV)",
    str_detect(tension, "A3") ~ "A3 (69 kV)",
    str_detect(tension, "B3") ~ "B3",
    tension == "A1" ~ "A1 (230 kV ou mais)",
    tension == "AS (Subterrâneo)" ~ "AS",
    TRUE ~ tension
  )
}

harmonize_class <- function(class) {
  case_when(
    str_detect(class, "Rural") ~ "Rural",
    str_detect(class, "Comercial") ~ "Commercial",
    str_detect(class, "Serviço Público") ~ "Public Service",
    str_detect(class, "Consumo Próprio") ~ "Own Consumption",
    str_detect(class, "Iluminação Pública") ~ "Public Lighting",
    str_detect(class, "Poder Público") ~ "Public Government",
    str_detect(class, "Residencial") ~ "Residential",
    TRUE ~ class
  )
}

samp_1991_2023 <- samp_1991_2023 %>%
  mutate(
    Tension = harmonize_tension(Tension),
    Class = harmonize_class(Class)
  )


# 6. Remove Invalid Rows
samp_1991_2023 <- samp_1991_2023 %>%
  filter(!grepl("^Applied filters:", Firm), !is.na(Firm))


#Create variable Tariff
df_1991_2023 <- samp_1991_2023 %>%
  mutate(Tariff = if_else(!is.na(ConsumptionEnergy) & ConsumptionEnergy>0 ,Revenue / ConsumptionEnergy, NA))

# Left Join with inflation based on "Year" and "Month"
df_joined <- left_join(df_1991_2023, ipca_monthly_trans, by = c("Year" = "Year", "Month" = "Month"))


# Deflate the Tariff variable
df_joined <-df_joined%>%mutate(Tariff_1223_BRL= Tariff*deflator122023,
                              Revenue_1223_BRL=Revenue*deflator122023,
                              revenue_tax_1223_BRL=RevenueTax*deflator122023,
                              tax_1223_BRL=Tax*deflator122023)


# create annual data set
df_1991_2023_deflated <- df_joined %>%
   group_by(Firm, Year, Tension, Class) %>%
   summarize(
     revenue = ifelse(all(is.na(Revenue_1223_BRL)), NA_real_, sum(Revenue_1223_BRL, na.rm = TRUE)),
     revenue_tax = ifelse(all(is.na(revenue_tax_1223_BRL)), NA_real_, sum(revenue_tax_1223_BRL, na.rm = TRUE)),
     consumption= ifelse(all(is.na(ConsumptionEnergy)), NA_real_, sum(ConsumptionEnergy, na.rm = TRUE)),
     consumers = ifelse(all(is.na(Consumers)), NA_real_, sum(Consumers, na.rm = TRUE)),
     tax = ifelse(all(is.na(tax_1223_BRL)), NA_real_, sum(tax_1223_BRL, na.rm = TRUE)))%>%
   mutate(Tariff_1223_BRL=revenue/consumption)


# Convert all names in the 'Firm' column to uppercase, otherwise some variables will be lost
df_1991_2023_deflated$Firm <- toupper(df_1991_2023_deflated$Firm)

#Harmonized names
df_1991_2023_deflated_names <- df_1991_2023_deflated %>%
  ungroup() %>%  # Remove any grouping
  left_join(df_names, by = c("Firm" = "Before_Privatization")) %>%
  mutate(Firm_Final = After_Privatization) %>%
  select(-After_Privatization) %>%
  filter(!is.na(Type)) %>%  # Exclude rows where Type is NA
  select(-Firm, -Type) # Remove columns `Firm` and `Type

df_1991_2023_deflated_names$Firm_Final <- toupper(df_1991_2023_deflated_names$Firm_Final)

# Save data (optional)
#write.csv(df_1991_2023_deflated_names, "ANEEL_SAMP_1991-2023.csv", row.names = FALSE)


```


# 2.2.  FEC & DEC - ANEEL
```{r}

# 1. File Reading and Combining
file_names <- c(paste0("DEC_FEC_Mensal_Distribuidora_", 2000:2023, ".xlsx"), 
                "data_DEC_1993-2016.xlsx", "data_FEC_1993-2016.xlsx")

data_list <- lapply(file_names, read_excel)
names(data_list) <- c(paste0("dec_fec_", 2000:2023), "dec_1993_2016", "fec_1993_2016")

# Combine 2000-2023 data
dec_fec_2000_2023 <- bind_rows(data_list[1:24])

# Rename columns in dec_fec_2000_2023
colnames(dec_fec_2000_2023) <- c(
  "Firm", "Type", "Year", "Month", "Consumers", "DEC", "FEC",
  "DECXP", "FECXP", "DECXN", "FECXN", "DECIP", "FECIP", "DECIND", "FECIND",
  "DECINE", "FECINE", "DECINC", "FECINC", "DECINO", "FECINO", "DECIPC", "FECIPC",
  "DECXPC", "FECXPC", "DECXNC", "FECXNC"
)

# 2. Data Cleaning and Processing
dec_fec_2000_2023 <- dec_fec_2000_2023 %>%
  filter(!grepl("^Applied filters:", Firm), !is.na(Firm)) %>%
  select(Firm, Type, Year, Month, Consumers, DEC, FEC) %>%
  filter(Type != "Permissão") %>%
  group_by(Year, Firm) %>%
  summarise(DEC = sum(DEC, na.rm = TRUE), FEC = sum(FEC, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(Firm = toupper(Firm)) %>%
  rename(SAIDI = DEC, SAIFI = FEC)

# 3. Prepare 1993-1996 Data
dec_1993_2016 <- data_list[["dec_1993_2016"]]
fec_1993_2016 <- data_list[["fec_1993_2016"]]

dec_1993_2016_long <- melt(setDT(dec_1993_2016), id.vars = "EMPRESA", variable.name = "Year") %>%
  rename(Firm = EMPRESA, SAIDI = value)

fec_1993_2016_long <- melt(setDT(fec_1993_2016), id.vars = "EMPRESA", variable.name = "Year") %>%
  rename(Firm = EMPRESA, SAIFI = value)

# Merge and process 1993-1999 data
dec_fec_1993_1999 <- left_join(fec_1993_2016_long, dec_1993_2016_long, by = c("Firm", "Year")) %>%
  mutate(Year = as.numeric(as.character(Year)), Firm = toupper(Firm)) %>%
  filter(Year < 2000)

# Harmonize names in 1993-1999 dataset
dec_fec_1993_1999_names <- dec_fec_1993_1999 %>%
  left_join(df_names, by = c("Firm" = "Before_Privatization"), relationship = "many-to-many") %>%
  mutate(Firm_Final = After_Privatization) %>%
  select(-After_Privatization) 

# Harmonize names in 2000-2023 dataset
dec_fec_2000_2023_names <- dec_fec_2000_2023 %>%
  left_join(df_names, by = c("Firm" = "Before_Privatization"), relationship = "many-to-many") %>%
  mutate(Firm_Final = After_Privatization) %>%
  select(-After_Privatization) 

# Merge harmonized datasets
dec_fec_1993_2023 <- bind_rows(dec_fec_1993_1999_names, dec_fec_2000_2023_names) %>% 
  select(-Type) %>% 
  select(-Firm) 

dec_fec_1993_2023$Firm_Final <- toupper(dec_fec_1993_2023$Firm_Final)

# Save data (optional)
# write.csv(fec_dec_1993_2023, "fec_dec_1993_2023.csv", row.names = FALSE)


```

## 2.3.  EMIS Next: 
```{r}

# 1. Set Working Directory
setwd("C:/Users/wb618493/OneDrive - WBG/Documents/ASA - Privitazation of Distribution/Brazil/Data/EMIS_financial_indicators_real")

# 2. Function to Process Financial Data
process_ratios <- function(company_name) {
  file_name <- paste0("Company_financials_ratios_", company_name, "_real.xlsx")
  ratios <- read_excel(file_name)[c(8, 18, 55), ] %>%
    t() %>%
    as.data.frame() %>%
    setNames(c("Year", "netprofit_margin", "debtequity_ratio")) %>%
    mutate(
      Year = as.numeric(format(as.Date(Year, format = "%Y"), "%Y")),
      Firm = company_name,
      netprofit_margin = as.numeric(gsub("%", "", netprofit_margin)),
      debtequity_ratio = as.numeric(gsub("%", "", debtequity_ratio))
    ) %>%
    select(Year, Firm, netprofit_margin, debtequity_ratio)
  return(ratios)
}

# 3. Process All Companies
companies <- c("COOPERALIANCA", "AmazonasEnergia", "AMPLA", "ELETROCAR", "CEB", "Ceee", "Celesc", "CELPA", 
               "CELTINS", "CEMAT", "CEMIG", "CERR", "CFLO", "CHESP", "CNEE", "Cocel", "Coelba", "Copel", 
               "Cosern", "Dcelt", "DEMEI", "DMED", "EDEVP", "EDP_ES", "EDP_SP", "EEB", "EFLJC", "EFLUL", 
               "Eletropaulo", "ELFSM", "EnelCE", "EnelSP", "EnergisaAC", "EnergisaBO", "EnergisaMinasRio", 
               "EnergisaNF", "EnergisaPB", "EnergisaRO", "EnergisaSE", "EnergisaSulSudeste", "ENERSUL", 
               "EquatorialAL", "EquatorialCEA", "EquatorialGO", "EquatorialMA", "EquatorialPI", "Forcel", 
               "Hidropan", "Jaguari", "Jari", "LestePaulista", "Light", "Mococa", "Muxfeldt", "Neoenergia_PE", 
               "NeoenergiaBR", "NovaPalma", "Pacto", "Paulista", "Piratininga", "RGE_Sul", "RoraimaEnergia", 
               "SantaCruz", "SULGIPE", "SulPaulista")  # Add more company names as needed


df_financial_1996_2023 <- lapply(companies, process_ratios) %>%
  bind_rows()%>%
  mutate(
    #Firm = if_else(Firm == "EnergisaSulSudeste" & Year < 2017, "CAIUA", Firm),
    Firm = toupper(Firm))



df_financial_1996_2023_names <- df_financial_1996_2023 %>%
  left_join(df_names, by = c("Firm" = "Before_Privatization"), relationship = "many-to-many") %>%
  mutate(Firm_Final = After_Privatization) %>%
  select(-After_Privatization) %>%
  select(-Firm) %>%
  select(-Type) %>%
  filter(!is.na(Year))  # Remove rows where Year is NA


df_financial_1996_2023_names$Firm_Final <- toupper(df_financial_1996_2023_names$Firm_Final)


# Save data (optional)
# write.csv(df_financial_1996_2023_names, "EMIS_1993_2023.csv", row.names = FALSE)

```


# 3. Join the datasets
```{r}

# Step 1: Select relevant columns from each dataset
# Deduplicate dec_fec_selected, and obtain the mean value in case of duplicates
dec_fec_selected <- dec_fec_1993_2023 %>%
  group_by(Year, Firm_Final) %>%
  summarize(across(everything(), ~ mean(.x, na.rm = TRUE)), .groups = "drop")

# Deduplicate df_financial_selected, and obtain the mean value in case of duplicates
df_financial_selected <- df_financial_1996_2023_names %>%
  group_by(Year, Firm_Final) %>%
  summarize(across(everything(), ~ mean(.x, na.rm = TRUE)), .groups = "drop")


# Step 2: Merge datasets
merged_data <- df_1991_2023_deflated_names %>%
  left_join(dec_fec_selected, by = c("Year", "Firm_Final")) %>%
  left_join(df_financial_selected, by = c("Year", "Firm_Final"))


# Step 1: Summarize SAIDI, SAIFI, and financial metrics by Year and Firm_Final
final_data <- merged_data %>%
  group_by(Year, Firm_Final, Tension, Class, Privatization.x) %>%
  summarise(
    # Weighted average for SAIDI (handle single-value groups)
    SAIDI = if (n() == 1) first(SAIDI) else weighted.mean(SAIDI, w = consumers, na.rm = TRUE),
    # Weighted average for SAIFI (handle single-value groups)
    SAIFI = if (n() == 1) first(SAIFI) else weighted.mean(SAIFI, w = consumers, na.rm = TRUE),
     # Handle single-value groups for netprofit_margin
    netprofit_margin = if (n() == 1) {
      if (!is.na(first(netprofit_margin))) first(netprofit_margin) else NA
    } else {
      mean(netprofit_margin, na.rm = TRUE)
    },
    # Handle single-value groups for debtequity_ratio
    debtequity_ratio = if (n() == 1) {
      if (!is.na(first(debtequity_ratio))) first(debtequity_ratio) else NA
    } else {
      mean(debtequity_ratio, na.rm = TRUE)
    },
    # Sum variables
    revenue = sum(revenue, na.rm = TRUE),
    revenue_tax = sum(revenue_tax, na.rm = TRUE),
    consumption = sum(consumption, na.rm = TRUE),
    consumers = sum(consumers, na.rm = TRUE),
    tax = sum(tax, na.rm = TRUE),
    .groups = "drop"
  )

final_data <- final_data %>%
  rename(
    Privatization = Privatization.x
  )


# Step 1: Summarize SAIDI, SAIFI, and financial metrics by Year and Firm_Final
final_data_firms <- final_data %>%
  group_by(Year, Firm_Final, Privatization) %>%
  summarise(
    # Weighted average for SAIDI (handle single-value groups)
    SAIDI = if (n() == 1) first(SAIDI) else weighted.mean(SAIDI, w = consumers, na.rm = TRUE),
    # Weighted average for SAIFI (handle single-value groups)
    SAIFI = if (n() == 1) first(SAIFI) else weighted.mean(SAIFI, w = consumers, na.rm = TRUE),
     # Handle single-value groups for netprofit_margin
    netprofit_margin = if (n() == 1) {
      if (!is.na(first(netprofit_margin))) first(netprofit_margin) else NA
    } else {
      mean(netprofit_margin, na.rm = TRUE)
    },
    # Handle single-value groups for debtequity_ratio
    debtequity_ratio = if (n() == 1) {
      if (!is.na(first(debtequity_ratio))) first(debtequity_ratio) else NA
    } else {
      mean(debtequity_ratio, na.rm = TRUE)
    },
    # Sum variables
    revenue = sum(revenue, na.rm = TRUE),
    revenue_tax = sum(revenue_tax, na.rm = TRUE),
    consumption = sum(consumption, na.rm = TRUE),
    consumers = sum(consumers, na.rm = TRUE),
    tax = sum(tax, na.rm = TRUE),
    .groups = "drop"
  )

#Set directory
setwd("C:/Users/wb618493/OneDrive - WBG/Documents/ASA - Privitazation of Distribution/Brazil/Data/DATA_ANEEL")

# Save data (optional)
write.csv(final_data, "final_data.csv", row.names = FALSE)

write.csv(final_data_firms, "final_data_firms.csv", row.names = FALSE)

```

